/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/8.0.2/userguide/multi_project_builds.html
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "bluetape4k"

include(rootProject.name + "-bom")
include(rootProject.name + "-core")

includeModules("data")
includeModules("io")
includeModules("kotlinx")
includeModules("quarkus")
includeModules("spring")
includeModules("test")
includeModules("tokenizer")
includeModules("utils")
includeModules("vertx")

// for example
includeModules("examples")

fun includeModules(baseDir: String) {
    files("$rootDir/$baseDir").files
        .filter { it.isDirectory }
        .forEach { moduleDir ->
            moduleDir.listFiles()
                ?.filter { it.isDirectory }
                ?.forEach { dir ->
                    val projectName = rootProject.name + "-" + baseDir + "-" + dir.name
                    // println("include modules: $projectName")

                    include(projectName)
                    project(":$projectName").projectDir = dir
                }
        }
}
