server:
    port: 8087
    address: 127.0.0.1

app:
    secret: secret
    refresh: refresh
    cors: http://localhost:8087
    first_user:
        username: "user@example.com"
        password: "userPassword"

spring:
    data:
        mongodb:
            uri: mongodb://${testcontainers.mongo.host}:${testcontainers.mongo.port}
            database: proddb
