package io.bluetape4k.openai.api.models.completion

import java.io.Serializable

/**
 * A completion generated by GPT-3.
 *
 * 참고: [create-completion](https://beta.openai.com/docs/api-reference/create-completion)
 *
 * @property text  The generated text. Will include the prompt if [CompletionRequest.echo] is true
 * @property index This index of this completion in the returned list.
 * @property logprobs  The log probabilities of the chosen tokens and the top [CompletionRequest.logprobs] tokens.
 * @property finishReason The reason why GPT-3 stopped generating, for example "length".
 */
data class Choice(
    val text: String,
    val index: Int,
    val logprobs: Logprobs? = null,
    val finishReason: String? = null,
) : Serializable
