/*
CREATE TABLE IF NOT EXISTS users
(
    id     INT GENERATED BY DEFAULT AS IDENTITY,
    name   VARCHAR(255) NOT NULL,
    login  VARCHAR(255) NOT NULL,
    email  VARCHAR(255) NOT NULL,
    avatar VARCHAR(255),

    PRIMARY KEY (id)
);

 */
truncate table users;

INSERT INTO users(`name`, `login`, `email`, `avatar`)
values ('User no 1', 'user1', 'user1@users.com', 'user1.png'),
       ('User no 2', 'user2', 'user2@users.com', 'user2.png'),
       ('User no 3', 'user3', 'user3@users.com', 'user3.png'),
       ('User no 4', 'user4', 'user4@users.com', 'user4.png');
