logging:
    level:
        root: INFO
        org.springframework.web: INFO
        org.springframework.security: INFO
#    org.springframework.boot.autoconfigure: DEBUG

jwt:
    private:
        key: classpath:private-key.pem
    public:
        key: classpath:public-key.pem
