spring:
    data:
        redis:
            repositories:
                enabled: true
    redis:
        host: ${testcontainers.redis.host}
        port: ${testcontainers.redis.port}

        lettuce:
            pool:
                enabled: true
                max-active: 32
                max-idle: 8
