test:
    #  hostport: httpbin.org:80
    #  hostport: localhost:5000
    #  uri: http://${test.hostport}
    uri: lb://httpbin  # https://nghttp2.org/httpbin/

logging:
    level:
        io.bluetape4k.workshop.bucket4j: debug
        com.giffing.bucket4j: debug

management:
    endpoints:
        web:
            exposure:
                include: "*"

spring:
    jmx:
        enabled: false
    cloud:
        gateway:
            default-filters:
                - PrefixPath=/httpbin
                - AddResponseHeader=X-Response-Default-Foo, Default-Bar

            routes:
                # =====================================
                # to run server
                # $ wscat --listen 9000
                # to run client
                # $ wscat --connect ws://localhost:8080/echo
                -   id: websocket_test
                    uri: ws://localhost:9000
                    order: 9000
                    predicates:
                        - Path=/echo
                # =====================================
                -   id: default_path_to_httpbin
                    uri: ${test.uri}
                    order: 10000
                    predicates:
                        - Path=/**
    data:
        redis:
            host: ${testcontainers.redis.host}
            port: ${testcontainers.redis.port}
            lettuce:
                pool:
                    enabled: true


bucket4j:
    enabled: true
    filters:
        -   cache-name: buckets
            filter-method: webflux
            url: .*
            http-content-type: application/json;charset=UTF-8
            http-response-body: '{ "name": "hello"}'
            http-response-headers:
                HELLO: WORLD
            filter-order: 1
            rate-limits:
                -   bandwidths:
                        -   capacity: 5
                            time: 10
                            unit: seconds
    cache-to-use: redis-lettuce
